baseURL = "https://baalajimaestro.me"
languageCode = "en-US"
title = "baalajimaestro"

enableEmoji = true
enableRobotsTXT = true
copyright = "© 2021 Maestro Creativescape."

[author]
name = "baalajimaestro"
image = "images/logo.webp"

 links = [
    { github = "https://github.com/baalajimaestro" },
    { gitlab = "https://gitlab.com/baalajimaestro" },
    { sourcehut = "https://git.sr.ht/~baalajimaestro" },
    { telegram = "https://t.me/baalajimaestro" },
    { discord = "https://discord.com/users/404797553272684555" },
    { instagram = "https://instagram.com/baalajimaestro" },
    { reddit = "https://reddit.com/user/baalajimaestro" },
    { twitter = "https://twitter.com/baalajimaestro" },
    { matrix = "https://matrix.to/#/@baalajimaestro:matrix.org" },
    { email = "mailto:me@baalajimaestro.me" },
  ]