baseURL = "https://baalajimaestro.me"
languageCode = "en-US"
title = "baalajimaestro"

enableEmoji = true
enableRobotsTXT = true
copyright = "Maestro Creativescape."

[author]
name = "baalajimaestro"
image = "images/logo.webp"

 links = [
  ]