languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

copyright = "&copy; 2022 Maestro Creativescape."
title = "baalajimaestro"

[author]
name = "baalajimaestro"
image = "logo.webp"
headline = "DevOps Engineer, and Self-taught System Administrator"