languageCode = "en"
languageName = "English"
weight = 1


copyright = "&copy; 2023 Maestro Creativescape."
title = "baalajimaestro"

[params]
  isoCode = "en"
  displayName = "EN"
  rtl = false
  dateFormat = "2 January 2006"