# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "congo"
# logo = "images/logo.png"
description = "baalajimaestro's personal website"
# mainSections = ["section1", "section2"]
# robots = ""

[homepage]
  layout = "custom" # valid options: page, profile, custom
  showRecent = false

[article]
  showDate = true
  dateFormat = "2 January 2006"
  showAuthor = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/baalajimaestro/personal-website/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  sharingLinks = ["facebook", "twitter", "reddit", "linkedin", "email", "telegram", "ycombinator"]

[list]
  showBreadcrumbs = false
  groupByYear = true

[taxonomy]
  showTermCount = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]