kind: pipeline
name: default
type: docker

steps:
- name: Static Site Builder
  image: equalos/hugo:extended-alpine
  commands:
  - apk update && apk add curl git go
  - sh push.sh
  environment:
    GITEA_TOKEN:
      from_secret: GITEA_TOKEN
