kind: pipeline
name: default
type: docker

steps:
- name: Static Site Builder
  image:  ghcr.io/peaceiris/hugo:latest
  commands:
  - apk update && apk add curl git go
  - sh push.sh
  environment:
    GITEA_TOKEN:
      from_secret: GITEA_TOKEN
