stages:
    - build-and-push
image:
    name: klakegg/hugo:ext-alpine
    entrypoint: [""]

before_script:
    - apk update && apk add python3 py3-pip git go
    - git config --global user.name baalajimaestro
    - git config --global user.email me@baalajimaestro.me
    - pip3 install GitPython
build-and-push:
    stage: build-and-push
    script:
        - python3 .buildpush.py
